#!/bin/sh

# These environment variables are sometimes needed by the running daemons
export USER=clnk
export HOME=/home/clnk

# Include the user-specific profile
. $HOME/.bash_profile

export PORT=62213
export UPLOAD_PREFIX=./incoming
export INTERNAL_PREFIX=/games-title-dl/

cd $HOME/html/images/games/Title.png

# Now let's go!
exec /home/clnk/bin/games-title-upload  2>&1
