#!/bin/sh

# These environment variables are sometimes needed by the running daemons
export USER=clnk
export HOME=/home/clnk

# Include the user-specific profile
. $HOME/.bash_profile

# Include settings.
. $HOME/env.sh

# Now let's go!
exec /home/clnk/bin/coffee /home/clnk/deploy/frontend/run.coffee 2>&1
