#!/bin/sh

# These environment variables are sometimes needed by the running daemons
export USER=clnk
export HOME=/home/clnk

# Include the user-specific profile
. $HOME/.bash_profile

# Include settings.
. $HOME/env.sh

# Local settings
export PORT=62681

# Now let's go!
exec node /home/clnk/deploy/frontend/run.js 2>&1
